// UI acceptance only: fixture files are diagnostic text, not real EPUB/ZIPs.
import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
assert.equal((await fetch('http://127.0.0.1:4399/health').then((r) => r.json())).fixture, true);
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_TEST_CHANNEL ? { channel: process.env.BROWSER_TEST_CHANNEL } : {}) });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  page.setDefaultTimeout(25000);
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  page.on('dialog', (dialog) => dialog.dismiss());
  const url = 'http://127.0.0.1:4398/books/88888888-8888-4888-8888-888888888888/publish';
  await page.goto(url);
  await page.getByLabel('Email').fill('author@example.test');
  await page.getByLabel('Password', { exact: true }).fill('fixture-password');
  await page.getByRole('button', { name: /sign in/i }).click();
  await page.getByRole('button', { name: 'New EPUB', exact: true }).click();
  await page.getByLabel('Add QR code').check();
  await page.getByLabel('HTTPS destination').fill('https://author.example/harbor');
  await page.getByLabel('QR label', { exact: true }).fill('Read more');
  await page.getByRole('button', { name: 'Save edition', exact: true }).click();
  await page.getByText('Edition settings saved.', { exact: true }).waitFor();
  await page.reload();
  await page.waitForFunction(() => [...document.querySelectorAll('input')].some((e) => e.value === 'https://author.example/harbor'));
  const packageButton = page.getByRole('button', { name: 'Create retailer package', exact: true });
  assert.equal(await packageButton.isEnabled(), false);
  await page.getByLabel('Preflight target').selectOption('kdp');
  await page.getByRole('button', { name: 'Render EPUB', exact: true }).click();
  await page.getByRole('link', { name: 'Download private file', exact: true }).waitFor();
  assert.equal(await packageButton.isEnabled(), false, 'packaging allowed before preflight');
  await page.getByRole('button', { name: 'Run preflight', exact: true }).click();
  await page.getByText('0 errors', { exact: true }).waitFor();
  await packageButton.click();
  const download = page.getByRole('link', { name: 'Download private ZIP', exact: true });
  await download.waitFor();
  const before = await download.getAttribute('href');
  const transfer = page.waitForEvent('download'); await download.click();
  assert.equal(await (await transfer).failure(), null, 'fixture download failed');
  await page.reload(); await download.waitFor();
  assert.notEqual(await download.getAttribute('href'), before, 'history did not refresh download URL');
  await page.getByRole('button', { name: 'New print', exact: true }).click();
  await page.getByLabel('Starting page number').fill('17');
  await page.getByRole('button', { name: 'Save edition', exact: true }).click();
  await page.getByText('Edition settings saved.', { exact: true }).waitFor();
  await page.getByLabel('Preflight target').selectOption('apple');
  assert.equal(await page.getByRole('button', { name: 'Run preflight', exact: true }).isEnabled(), false, 'print accepted for Apple');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'publishing mobile overflow');
  assert.deepEqual(errors, []);
  console.log('PASS publishing browser: save/reload QR, render, preflight gate, matching package source, download/history renewal, print start, retailer compatibility, mobile. Artifact bytes remain fixtures.');
} finally { await browser.close(); }
